sudo: required

language: c

services:
  - docker

before_install:
  - docker pull gapsystem/gap-docker

script:
  - docker version
  - docker run -t gapsystem/gap-container sh -c 'wget https://raw.githubusercontent.com/gap-system/gap-container-travis/master/homophony.g ; /home/gap/inst/gap4r7/bin/gap.sh homophony.g'

